export const articles = [
  {
    id: 1,
    title: 'Lorem ipsum dolor sit amet',
    body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nisl nunc mi ipsum faucibus. Ut pharetra sit amet aliquam. Ipsum nunc aliquet bibendum enim facilisis. Pretium aenean pharetra magna ac placerat. Velit euismod in pellentesque massa placerat duis ultricies lacus sed. Sed libero enim sed faucibus turpis in eu mi. Lectus urna duis convallis convallis tellus. Nulla malesuada pellentesque elit eget gravida cum sociis natoque penatibus. Neque viverra justo nec ultrices dui sapien eget mi. Pharetra sit amet aliquam id diam maecenas ultricies mi. Egestas pretium aenean pharetra magna ac placerat. Eu lobortis elementum nibh tellus molestie nunc. Euismod quis viverra nibh cras pulvinar. Est ullamcorper eget nulla facilisi etiam dignissim diam quis. Blandit cursus risus at ultrices mi tempus imperdiet nulla malesuada. Hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit. Posuere morbi leo urna molestie. Ac turpis egestas sed tempus urna. Nunc id cursus metus aliquam.'
  },
  {
    id: 2,
    title: 'Lorem ipsum dolor sit amet',
    body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nisl nunc mi ipsum faucibus. Ut pharetra sit amet aliquam. Ipsum nunc aliquet bibendum enim facilisis. Pretium aenean pharetra magna ac placerat. Velit euismod in pellentesque massa placerat duis ultricies lacus sed. Sed libero enim sed faucibus turpis in eu mi. Lectus urna duis convallis convallis tellus. Nulla malesuada pellentesque elit eget gravida cum sociis natoque penatibus. Neque viverra justo nec ultrices dui sapien eget mi. Pharetra sit amet aliquam id diam maecenas ultricies mi. Egestas pretium aenean pharetra magna ac placerat. Eu lobortis elementum nibh tellus molestie nunc. Euismod quis viverra nibh cras pulvinar. Est ullamcorper eget nulla facilisi etiam dignissim diam quis. Blandit cursus risus at ultrices mi tempus imperdiet nulla malesuada. Hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit. Posuere morbi leo urna molestie. Ac turpis egestas sed tempus urna. Nunc id cursus metus aliquam.'
  },
  {
    id: 3,
    title: 'Lorem ipsum dolor sit amet',
    body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nisl nunc mi ipsum faucibus. Ut pharetra sit amet aliquam. Ipsum nunc aliquet bibendum enim facilisis. Pretium aenean pharetra magna ac placerat. Velit euismod in pellentesque massa placerat duis ultricies lacus sed. Sed libero enim sed faucibus turpis in eu mi. Lectus urna duis convallis convallis tellus. Nulla malesuada pellentesque elit eget gravida cum sociis natoque penatibus. Neque viverra justo nec ultrices dui sapien eget mi. Pharetra sit amet aliquam id diam maecenas ultricies mi. Egestas pretium aenean pharetra magna ac placerat. Eu lobortis elementum nibh tellus molestie nunc. Euismod quis viverra nibh cras pulvinar. Est ullamcorper eget nulla facilisi etiam dignissim diam quis. Blandit cursus risus at ultrices mi tempus imperdiet nulla malesuada. Hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit. Posuere morbi leo urna molestie. Ac turpis egestas sed tempus urna. Nunc id cursus metus aliquam.'
  },
  {
    id: 4,
     title: 'Lorem ipsum dolor sit amet',
    body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nisl nunc mi ipsum faucibus. Ut pharetra sit amet aliquam. Ipsum nunc aliquet bibendum enim facilisis. Pretium aenean pharetra magna ac placerat. Velit euismod in pellentesque massa placerat duis ultricies lacus sed. Sed libero enim sed faucibus turpis in eu mi. Lectus urna duis convallis convallis tellus. Nulla malesuada pellentesque elit eget gravida cum sociis natoque penatibus. Neque viverra justo nec ultrices dui sapien eget mi. Pharetra sit amet aliquam id diam maecenas ultricies mi. Egestas pretium aenean pharetra magna ac placerat. Eu lobortis elementum nibh tellus molestie nunc. Euismod quis viverra nibh cras pulvinar. Est ullamcorper eget nulla facilisi etiam dignissim diam quis. Blandit cursus risus at ultrices mi tempus imperdiet nulla malesuada. Hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit. Posuere morbi leo urna molestie. Ac turpis egestas sed tempus urna. Nunc id cursus metus aliquam.'
  },
  {
    id: 5,
     title: 'Lorem ipsum dolor sit amet',
    body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nisl nunc mi ipsum faucibus. Ut pharetra sit amet aliquam. Ipsum nunc aliquet bibendum enim facilisis. Pretium aenean pharetra magna ac placerat. Velit euismod in pellentesque massa placerat duis ultricies lacus sed. Sed libero enim sed faucibus turpis in eu mi. Lectus urna duis convallis convallis tellus. Nulla malesuada pellentesque elit eget gravida cum sociis natoque penatibus. Neque viverra justo nec ultrices dui sapien eget mi. Pharetra sit amet aliquam id diam maecenas ultricies mi. Egestas pretium aenean pharetra magna ac placerat. Eu lobortis elementum nibh tellus molestie nunc. Euismod quis viverra nibh cras pulvinar. Est ullamcorper eget nulla facilisi etiam dignissim diam quis. Blandit cursus risus at ultrices mi tempus imperdiet nulla malesuada. Hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit. Posuere morbi leo urna molestie. Ac turpis egestas sed tempus urna. Nunc id cursus metus aliquam.'
  },
  {
    id: 6,
     title: 'Lorem ipsum dolor sit amet',
    body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nisl nunc mi ipsum faucibus. Ut pharetra sit amet aliquam. Ipsum nunc aliquet bibendum enim facilisis. Pretium aenean pharetra magna ac placerat. Velit euismod in pellentesque massa placerat duis ultricies lacus sed. Sed libero enim sed faucibus turpis in eu mi. Lectus urna duis convallis convallis tellus. Nulla malesuada pellentesque elit eget gravida cum sociis natoque penatibus. Neque viverra justo nec ultrices dui sapien eget mi. Pharetra sit amet aliquam id diam maecenas ultricies mi. Egestas pretium aenean pharetra magna ac placerat. Eu lobortis elementum nibh tellus molestie nunc. Euismod quis viverra nibh cras pulvinar. Est ullamcorper eget nulla facilisi etiam dignissim diam quis. Blandit cursus risus at ultrices mi tempus imperdiet nulla malesuada. Hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit. Posuere morbi leo urna molestie. Ac turpis egestas sed tempus urna. Nunc id cursus metus aliquam.'
  }
];